[build]
target = "./index.html"
dist = "dist"

[watch]
ignore = ["./src-tauri"]

[serve]
address = "127.0.0.1"
port = 1420
open = false

[[hooks]]
stage = "build"
command = "sh"
command_arguments = [
    "-c",
    "npx tailwindcss-cli build -i src/tailwind.css -o $TRUNK_STAGING_DIR/tailwind.css",
]
